# Generated by Django 5.0.6 on 2024-06-19 13:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='名前')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('description', models.CharField(max_length=500, verbose_name='店舗説明')),
                ('start_at', models.TimeField(default=django.utils.timezone.now, verbose_name='営業開始時間')),
                ('end_at', models.TimeField(default=django.utils.timezone.now, verbose_name='営業終了時間')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nagoyameshiapp.category', verbose_name='カテゴリ')),
            ],
        ),
    ]
