# Generated by Django 5.0.6 on 2024-06-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='nagoyameshiapp/restaurant/image/', verbose_name='画像'),
        ),
    ]
